# syntax=docker/dockerfile:1

FROM ubuntu:mantic
WORKDIR /app
COPY . .

RUN apt-get update && apt-get upgrade -y
RUN apt-get install python3 python3-venv python3-pip -y
RUN python3 -m venv .venv
RUN . ./.venv/bin/activate
RUN ./.venv/bin/pip install -r requirements.txt

CMD [".", "./.venv/bin/activate"]
CMD ["./.venv/bin/python","./app.py"]

EXPOSE 5000
